version: 2

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  target-branch: dev
  versioning-strategy: increase
  reviewers:
  - dmcollom
  - phycodurus
  ignore:
  - dependency-name: numpy
    versions:
    - 1.20.0
    - 1.20.1
  - dependency-name: astroplan
    versions:
    - "0.8"
  - dependency-name: astropy
    versions:
    - "4.2"
