language: python
python:
    - '3.6'
    - '3.7'
    - '3.8'
os:
  - linux
dist: xenial
sudo: true

before_install:
    - sudo apt-get install -y gfortran
    - pip uninstall -y numpy    

stages:
    - style_check
    - test
    # - name: deploy_alpha
    #   if: branch = development

jobs:
  include:
      - stage: style_check
        name: "Code style check"
        python: 3.8
        install:
          - pip install -I pycodestyle
        script:
          - pycodestyle tom_* --exclude=*/migrations/* --max-line-length=120
      - stage: test
        name: "Unit tests"
        install:
          - pip install -I -r requirements.txt
        script:
          - python3 manage.py test
      # - stage: deploy
  

# before_deploy:
#     if ! [[ $TRAVIS_BRANCH ]]

# Deploy alpha releases to PyPi on tags of dev branch
deploy:
    provider: pypi
    branch: development
    skip_existing: true
    on:
        tags: true
    user: "__token__"
    password:
        secure: "W11OdJOvj9hvdEsJB48SuPOvylT0awsSG2wScYdtM+mnFx6u5pv7/0oxz0nyhr2/1xD+Mz7QBy5wH2ijXcpruhHwm7loopaB9Lc28au3vnVuDgwdU3yUttXjjzmPHh+q3ggsjAJS7aV4X4CKl0/cM9h3MTsr91MiIvta0cjiPYBTn/3YTrVyO+VypQnsnC2bV7bj1H/c6hYi6mzq4xKtpM1QSMs5baWo7vui1LqbHGeZSID+r9Z3Zx8c8UyAbDG9Qhqi2+TyZxhond1R13IrGtIlvjey87aCnlOFwnA+CXPAbTWsUxq+gE+QO7BCAA2oMZGkLgVeCgHmEHf8gPU/N+XEpdh9FEmgaoU7LIrPOjQI+4ijhEoadhpUxHaQG0j2qhHeE4THz+dfV0XQVPUlzAwX5ZQyLwbAHje8E1wdeqS+pPzodIB18Vtw6Lz0c2ppmieXB1IiSSG0nnxcuLgyFJ/tYJyp63+5fCLK/Itafn3SLT1HRNS/PccbZdUo5L4oFKQsMXgIU9v33Z59CyXpPiNruC+AEwujuEcDrZN1/pYc8+Zmgh42fx+qHZ3/2QitKopl+XMRMnz6X7JIS2QTgY74aLBp/djv5DHtTJnN1cdZ8wMo8K515R/p+C5HboMh9bNEM+imL8pk6Whw9QMGapNoNst99aQz4fUz3n6sPr0="
    distributions: "sdist bdist_wheel"

# Deploy to PyPi on tags of master branch
deploy:
    provider: pypi
    branch: master
    on:
      tags: true
    skip_existing:
      true:
    user: "__token__"
    password:
      secure: "W11OdJOvj9hvdEsJB48SuPOvylT0awsSG2wScYdtM+mnFx6u5pv7/0oxz0nyhr2/1xD+Mz7QBy5wH2ijXcpruhHwm7loopaB9Lc28au3vnVuDgwdU3yUttXjjzmPHh+q3ggsjAJS7aV4X4CKl0/cM9h3MTsr91MiIvta0cjiPYBTn/3YTrVyO+VypQnsnC2bV7bj1H/c6hYi6mzq4xKtpM1QSMs5baWo7vui1LqbHGeZSID+r9Z3Zx8c8UyAbDG9Qhqi2+TyZxhond1R13IrGtIlvjey87aCnlOFwnA+CXPAbTWsUxq+gE+QO7BCAA2oMZGkLgVeCgHmEHf8gPU/N+XEpdh9FEmgaoU7LIrPOjQI+4ijhEoadhpUxHaQG0j2qhHeE4THz+dfV0XQVPUlzAwX5ZQyLwbAHje8E1wdeqS+pPzodIB18Vtw6Lz0c2ppmieXB1IiSSG0nnxcuLgyFJ/tYJyp63+5fCLK/Itafn3SLT1HRNS/PccbZdUo5L4oFKQsMXgIU9v33Z59CyXpPiNruC+AEwujuEcDrZN1/pYc8+Zmgh42fx+qHZ3/2QitKopl+XMRMnz6X7JIS2QTgY74aLBp/djv5DHtTJnN1cdZ8wMo8K515R/p+C5HboMh9bNEM+imL8pk6Whw9QMGapNoNst99aQz4fUz3n6sPr0="

# # Deploy release candidates to PyPi on pushes/merges to master branch
# deploy:
#     provider: pypi
#     branch: master
#     skip_existing: true
#     on:
#         tags: false
#     user: "__token__"
#     password:
#         secure: "QK0IxvFGrZsA4mJK/MWQ34kXmpDEpH1ckuq1HPP/Kr3p/11VgEsNWwkkXY8kFiOS35S073XYJo4VrUUxZ9xeRNIvG1JgySfqiO+GGUsp3Lx4AP7pOcsb9NfgSVt8ekq/HS1/gzJaFuXvx7CZk3aR/RLKWoHZ1PHzxq2010QGtIRcMMKXOtk6pIE8rveoTe9hHG+cwdEDvuI7q485y9Wop1nN58QcFxIvf8DBhdXDXov50iWleLQzPXIDShuYJGQMfK68JUqGXZrXdEA6oyGU+VGTGgyXPPRvRQLZqZtXsI3Ex8fwyaFN7z1BtiJXgnp84viA03lAlLofTSAwFkS/1krAvz9LKTzv/HwynkcMZtNAFWBytaugFpkLbSA3S+jDnVUgMP6RE4dQSo39l3+LDGyl04u2rgy8GcWJJdlup0Z4NFhKKIm6eBaZw6Yzedk+VVahglEHFlOnWZejvWoz1m57Sj54eh2TKeLXT7wVnVeI4vEl3WdBO2/MZagfWfTjRai3N/TPoq7kNlkgUPKM960VTbG0jVupm+IVYmLCKTtkcpWQbX+Rk8kZv/ujQYg/cqTvJr5rjL7OvxEurzXMSDDi0BmCEFyq5WbYWRi93hgsNSph9HrDZl5VAIKEnEgbL7FvAslX+b1OwPMJh8DukSWVZs2a+UYxOEyd1BCpxZo="
