language: python
python:
    - '3.7'
dist: xenial
sudo: true
before_install:
    - sudo apt-get install -y gfortran
install:
    - pip install -r requirements.txt
script:
    - python3 manage.py test
