language: python
python:
  - '3.8'
  - '3.7'
  - '3.6'
os:
  - linux
dist: bionic

before_install:
  - sudo apt-get install -y gfortran
  - pip uninstall -y numpy   

script:
  - python3 manage.py test

jobs:
  include:
    - stage: "Style Checks"
      install: pip install -I pycodestyle
      script: pycodestyle tom_* --exclude=*/migrations/* --max-line-length=120

    - stage: "Tests on MacOS"
      os: osx
      language: shell

    # Deploy alpha releases to PyPi and generate draft release on Github Releases (incomplete)
    - stage: "Deploy Development"
      script: skip
      deploy:
        provider: pypi
        branch: development
        skip_existing: true
        cleanup: false
        on:
          tags: true
          condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+\-(alpha)\.[0-9]+$
        user: "__token__"
        password:
           secure: "W11OdJOvj9hvdEsJB48SuPOvylT0awsSG2wScYdtM+mnFx6u5pv7/0oxz0nyhr2/1xD+Mz7QBy5wH2ijXcpruhHwm7loopaB9Lc28au3vnVuDgwdU3yUttXjjzmPHh+q3ggsjAJS7aV4X4CKl0/cM9h3MTsr91MiIvta0cjiPYBTn/3YTrVyO+VypQnsnC2bV7bj1H/c6hYi6mzq4xKtpM1QSMs5baWo7vui1LqbHGeZSID+r9Z3Zx8c8UyAbDG9Qhqi2+TyZxhond1R13IrGtIlvjey87aCnlOFwnA+CXPAbTWsUxq+gE+QO7BCAA2oMZGkLgVeCgHmEHf8gPU/N+XEpdh9FEmgaoU7LIrPOjQI+4ijhEoadhpUxHaQG0j2qhHeE4THz+dfV0XQVPUlzAwX5ZQyLwbAHje8E1wdeqS+pPzodIB18Vtw6Lz0c2ppmieXB1IiSSG0nnxcuLgyFJ/tYJyp63+5fCLK/Itafn3SLT1HRNS/PccbZdUo5L4oFKQsMXgIU9v33Z59CyXpPiNruC+AEwujuEcDrZN1/pYc8+Zmgh42fx+qHZ3/2QitKopl+XMRMnz6X7JIS2QTgY74aLBp/djv5DHtTJnN1cdZ8wMo8K515R/p+C5HboMh9bNEM+imL8pk6Whw9QMGapNoNst99aQz4fUz3n6sPr0="
        distributions: "sdist bdist_wheel"

    # - stage: "Deploy Development"
    #   python: 3.8
    #   deploy:
    #     provider: releases
    #     api_key: ""
    #     branch:
    #       - development
    #     on:
    #       tags: true
    #     file_glob: true
    #     file: dist/*
    #     cleanup: false
    #     draft: true
    #     prerelease: true

    # Deploy full releases to PyPi and generate draft release on Github Releases (incomplete)
    - stage: "Deploy Master"
      python: 3.8
      script: skip
      deploy:
        provider: pypi
        branch: master
        skip_existing: true
        cleanup: false
        on:
          tags: true
          condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
        user: "__token__"
        password:
          secure: "W11OdJOvj9hvdEsJB48SuPOvylT0awsSG2wScYdtM+mnFx6u5pv7/0oxz0nyhr2/1xD+Mz7QBy5wH2ijXcpruhHwm7loopaB9Lc28au3vnVuDgwdU3yUttXjjzmPHh+q3ggsjAJS7aV4X4CKl0/cM9h3MTsr91MiIvta0cjiPYBTn/3YTrVyO+VypQnsnC2bV7bj1H/c6hYi6mzq4xKtpM1QSMs5baWo7vui1LqbHGeZSID+r9Z3Zx8c8UyAbDG9Qhqi2+TyZxhond1R13IrGtIlvjey87aCnlOFwnA+CXPAbTWsUxq+gE+QO7BCAA2oMZGkLgVeCgHmEHf8gPU/N+XEpdh9FEmgaoU7LIrPOjQI+4ijhEoadhpUxHaQG0j2qhHeE4THz+dfV0XQVPUlzAwX5ZQyLwbAHje8E1wdeqS+pPzodIB18Vtw6Lz0c2ppmieXB1IiSSG0nnxcuLgyFJ/tYJyp63+5fCLK/Itafn3SLT1HRNS/PccbZdUo5L4oFKQsMXgIU9v33Z59CyXpPiNruC+AEwujuEcDrZN1/pYc8+Zmgh42fx+qHZ3/2QitKopl+XMRMnz6X7JIS2QTgY74aLBp/djv5DHtTJnN1cdZ8wMo8K515R/p+C5HboMh9bNEM+imL8pk6Whw9QMGapNoNst99aQz4fUz3n6sPr0="
        distributions: "sdist bdist_wheel"

    # - stage: "Deploy Master"
    #   python: 3.8
    #   deploy:
    #     provider: releases
    #     api_key: ""
    #     branch:
    #       - master
    #     on:
    #       tags: true
    #     file_glob: true
    #     file: dist/*
    #     cleanup: false
    #     draft: true
