# Generated by Django 4.0.4 on 2024-03-08 15:49

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bhtom_targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility', models.CharField(max_length=50)),
                ('parameters', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('facilities', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=200), blank=True, default=list, size=None)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('active_from', models.DateField()),
                ('active_to', models.DateField()),
                ('comments', models.CharField(blank=True, max_length=2048, null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-active_to', '-active_from'),
            },
        ),
        migrations.CreateModel(
            name='ObservationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=50)),
                ('parameters', models.JSONField()),
                ('observation_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=200)),
                ('scheduled_start', models.DateTimeField(null=True)),
                ('scheduled_end', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bhtom_observations.proposal')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom_targets.target')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ObservationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('observation_records', models.ManyToManyField(to='bhtom_observations.observationrecord')),
            ],
            options={
                'ordering': ('-created', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DynamicCadence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence_strategy', models.CharField(default=None, max_length=100, verbose_name='Cadence strategy used for this DynamicCadence')),
                ('cadence_parameters', models.JSONField(verbose_name='Cadence-specific parameters')),
                ('active', models.BooleanField(help_text='Whether or not this DynamicCadence should\n                                           continue to submit observations.', verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The time which this DynamicCadence was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The time which this DynamicCadence was modified.')),
                ('observation_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bhtom_observations.observationgroup')),
            ],
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.CheckConstraint(check=models.Q(('active_to__gt', django.db.models.expressions.F('active_from'))), name='check_active_dates'),
        ),
    ]
