# Generated by Django 4.0.4 on 2024-05-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_targets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='description'),
        ),
    ]
