# Generated by Django 4.0.4 on 2024-08-27 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bhtom_targets', '0002_alter_target_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The time which this record was created in the TOM database.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The time which this record was changed in the TOM database.', verbose_name='Last Modified')),
                ('download_type', models.CharField(choices=[('R', 'RADIO'), ('P', 'PHOTOMETRY')], default='P', max_length=1)),
                ('ip_address', models.CharField(max_length=25)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom_targets.target')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created', 'target'),
            },
        ),
    ]
