# Generated by Django 4.0.4 on 2024-02-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_targets', '0002_alter_target_cadence_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetname',
            name='source_name',
            field=models.CharField(choices=[('GAIA_ALERTS', 'Gaia Alerts name'), ('CPCS', 'CPCS name'), ('ASASSN', 'ASASSN name'), ('OGLE_EWS', 'OGLE-EWS name'), ('ZTF', 'ZTF name'), ('ATLAS', 'ATLAS name'), ('AAVSO', 'AAVSO name'), ('TNS', 'TNS name'), ('ANTARES', 'ANTARES name'), ('ZTF_DR8', 'ZTF DR8 name'), ('SDSS', 'SDSS name'), ('NEOWISE', 'NEOWISE name'), ('ALLWISE', 'ALLWISE name'), ('CRTS', 'CRTS name'), ('LINEAR', 'LINEAR name'), ('FIRST', 'FIRST name'), ('PS1', 'PS1 name'), ('DECAPS', 'DECAPS name'), ('GAIA_DR3', 'Gaia DR3 name'), ('GAIA_DR2', 'Gaia DR2 name'), ('KMT_NET', 'KMT-NET name'), ('LOFAR', 'LOFAR2m name'), ('twomass', '2MASS name'), ('PTF', 'PTF name')], max_length=100, verbose_name='Source Name'),
        ),
    ]
