# Generated by Django 4.0.4 on 2025-03-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_targets', '0003_downloadedtarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='cadence',
            field=models.FloatField(default=0, help_text='Requested cadence in days (0 - target does not require follow-up observations)', verbose_name='cadence'),
        ),
        migrations.AlterField(
            model_name='target',
            name='classification',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Be-star outburst', 'Be-star outburst'), ('AGN', 'Active Galactic Nucleus(AGN)'), ('BL Lac', 'BL Lac'), ('CV', 'Cataclysmic Variable(CV)'), ('CEPH', 'Cepheid Variable(CEPH)'), ('EB', 'Eclipsing Binary(EB)'), ('Galaxy', 'Galaxy'), ('LPV', 'Long Period Variable(LPV)'), ('LBV', 'Luminous Blue Variable(LBV)'), ('M-dwarf flare', 'M-dwarf flare'), ('Microlensing Event', 'Microlensing Event'), ('Nova', 'Nova'), ('Peculiar Supernova', 'Peculiar Supernova'), ('QSO', 'Quasar(QSO)'), ('RCrB', 'R CrB Variable'), ('RR Lyrae Variable', 'RR Lyrae Variable'), ('SSO', 'Solar System Object(SSO)'), ('Star', 'Star'), ('SN', 'Supernova(SN)'), ('Supernova imposter', 'Supernova imposter'), ('Symbiotic star', 'Symbiotic star'), ('TDE', 'Tidal Disruption Event(TDE)'), ('Variable star-other', 'Variable star-other'), ('XRB', 'X-Ray Binary(XRB)'), ('YSO', 'Young Stellar Object(YSO)')], db_index=True, max_length=50, null=True, verbose_name='classification'),
        ),
        migrations.AlterField(
            model_name='target',
            name='importance',
            field=models.FloatField(db_index=True, default=0, help_text='Target importance as a float: 10 - target requested for immediate observations, 0 - no need for follow-up observations.', verbose_name='importance'),
        ),
    ]
