# Generated by Django 4.0.4 on 2025-06-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_targets', '0004_alter_target_cadence_alter_target_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='classification',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Be-star outburst', 'Be-star outburst'), ('AGN', 'Active Galactic Nucleus(AGN)'), ('BL Lac', 'BL Lac'), ('CV', 'Cataclysmic Variable(CV)'), ('CEPH', 'Cepheid Variable(CEPH)'), ('EB', 'Eclipsing Binary(EB)'), ('Galaxy', 'Galaxy'), ('GWOC', 'Gravitational Wave Optical Counterpart (GWOC)'), ('LPV', 'Long Period Variable(LPV)'), ('LBV', 'Luminous Blue Variable(LBV)'), ('M-dwarf flare', 'M-dwarf flare'), ('Microlensing Event', 'Microlensing Event'), ('Nova', 'Nova'), ('Peculiar Supernova', 'Peculiar Supernova'), ('QSO', 'Quasar(QSO)'), ('RCrB', 'R CrB Variable'), ('RR Lyrae Variable', 'RR Lyrae Variable'), ('SSO', 'Solar System Object(SSO)'), ('Star', 'Star'), ('SN', 'Supernova(SN)'), ('SLSN', 'Super Luminous Supernova (SLSN)'), ('Supernova impostor', 'Supernova impostor'), ('Symbiotic star', 'Symbiotic star'), ('TDE', 'Tidal Disruption Event(TDE)'), ('Variable star-other', 'Variable star-other'), ('XRB', 'X-Ray Binary(XRB)'), ('Xray-transient', 'X-Ray Transient'), ('YSO', 'Young Stellar Object(YSO)')], db_index=True, max_length=50, null=True, verbose_name='classification'),
        ),
    ]
