# Generated by Django 4.0.4 on 2025-07-28 09:56

import bhtom_base.bhtom_targets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_targets', '0005_alter_target_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='data_plot',
            field=models.DateTimeField(blank=True, max_length=300, null=True, verbose_name='creation plot date'),
        ),
        migrations.AlterField(
            model_name='target',
            name='photometry_icon_plot',
            field=models.FileField(blank=True, default=None, max_length=300, null=True, upload_to=bhtom_base.bhtom_targets.models.Target.photometry_icon_plot_path),
        ),
        migrations.AlterField(
            model_name='target',
            name='photometry_plot',
            field=models.FileField(blank=True, default=None, max_length=300, null=True, upload_to=bhtom_base.bhtom_targets.models.Target.photometry_plot_path),
        ),
        migrations.AlterField(
            model_name='target',
            name='photometry_plot_obs',
            field=models.FileField(blank=True, default=None, max_length=300, null=True, upload_to=bhtom_base.bhtom_targets.models.Target.photometry_plot_obs_path),
        ),
        migrations.AlterField(
            model_name='target',
            name='spectroscopy_plot',
            field=models.FileField(blank=True, default=None, max_length=300, null=True, upload_to=bhtom_base.bhtom_targets.models.Target.spectroscopy_plot_path),
        ),
    ]
