# Generated by Django 4.0.4 on 2026-01-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_targets', '0009_alter_targetname_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='has_gamma',
            field=models.BooleanField(default=False, help_text='True when the target has gamma-ray data.', verbose_name='has gamma'),
        ),
        migrations.AddField(
            model_name='target',
            name='has_infrared',
            field=models.BooleanField(default=False, help_text='True when the target has infrared data.', verbose_name='has infrared'),
        ),
        migrations.AddField(
            model_name='target',
            name='has_optical',
            field=models.BooleanField(default=False, help_text='True when the target has optical data.', verbose_name='has optical'),
        ),
        migrations.AddField(
            model_name='target',
            name='has_polarimetry',
            field=models.BooleanField(default=False, help_text='True when the target has polarimetry data.', verbose_name='has polarimetry'),
        ),
        migrations.AddField(
            model_name='target',
            name='has_radio',
            field=models.BooleanField(default=False, help_text='True when the target has radio data.', verbose_name='has radio'),
        ),
        migrations.AddField(
            model_name='target',
            name='has_xray',
            field=models.BooleanField(default=False, help_text='True when the target has X-ray data.', verbose_name='has X-ray'),
        ),
        migrations.AlterField(
            model_name='targetname',
            name='source_name',
            field=models.CharField(choices=[('GAIA_ALERTS', 'Gaia Alerts name'), ('CPCS', 'CPCS name'), ('ASASSN', 'ASASSN name'), ('OGLE_EWS', 'OGLE-EWS name'), ('ZTF', 'ZTF name'), ('ATLAS', 'ATLAS name'), ('AAVSO', 'AAVSO name'), ('TNS', 'TNS name'), ('ANTARES', 'ANTARES name'), ('ZTF_DR8', 'ZTF DR8 name'), ('SDSS', 'SDSS name'), ('NEOWISE', 'NEOWISE name'), ('ALLWISE', 'ALLWISE name'), ('CRTS', 'CRTS name'), ('LINEAR', 'LINEAR name'), ('FIRST', 'FIRST name'), ('PS1', 'PS1 name'), ('DECAPS', 'DECAPS name'), ('GAIA_DR3', 'Gaia DR3 name'), ('GAIA_DR2', 'Gaia DR2 name'), ('KMT_NET', 'KMT-NET name'), ('LOFAR', 'LOFAR2m name'), ('twomass', '2MASS name'), ('PTF', 'PTF name'), ('OGLE_OCVS', 'OGLE OCVS  name'), ('ASTRO_COLIBRI', 'Astro COLIBRI name'), ('GALEX', 'GALEX name'), ('SWIFT_UVOT', 'SwiftUVOT name')], max_length=100, verbose_name='Source Name'),
        ),
    ]
