# Generated by Django 4.0.4 on 2026-01-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_targets', '0010_target_has_gamma_target_has_infrared_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='has_gamma',
            field=models.BooleanField(blank=True, default=False, help_text='True when the target has gamma-ray data.', null=True, verbose_name='has gamma'),
        ),
        migrations.AlterField(
            model_name='target',
            name='has_infrared',
            field=models.BooleanField(blank=True, default=False, help_text='True when the target has infrared data.', null=True, verbose_name='has infrared'),
        ),
        migrations.AlterField(
            model_name='target',
            name='has_optical',
            field=models.BooleanField(default=False, help_text='True when the target has optical data.', null=True, verbose_name='has optical'),
        ),
        migrations.AlterField(
            model_name='target',
            name='has_polarimetry',
            field=models.BooleanField(blank=True, default=False, help_text='True when the target has polarimetry data.', null=True, verbose_name='has polarimetry'),
        ),
        migrations.AlterField(
            model_name='target',
            name='has_radio',
            field=models.BooleanField(blank=True, default=False, help_text='True when the target has radio data.', null=True, verbose_name='has radio'),
        ),
        migrations.AlterField(
            model_name='target',
            name='has_xray',
            field=models.BooleanField(blank=True, default=False, help_text='True when the target has X-ray data.', null=True, verbose_name='has X-ray'),
        ),
    ]
