# Generated by Django 4.0.4 on 2026-02-06 10:13

import bhtom_base.bhtom_targets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_targets', '0011_alter_target_has_gamma_alter_target_has_infrared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='photometry_plot_highenergy',
            field=models.FileField(blank=True, default=None, max_length=300, null=True, upload_to=bhtom_base.bhtom_targets.models.Target.photometry_plot_highenergy_path),
        ),
    ]
