# Generated by Django 4.0.4 on 2023-10-12 15:05

import bhtom_base.bhtom_dataproducts.models
import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bhtom_observatory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bhtom_targets', '0001_initial'),
        ('bhtom_observations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('private', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DataProductGroup_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active_flg', models.BooleanField(db_index=True, default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom_dataproducts.dataproductgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(help_text='Data product identifier used by the source of the data product.', max_length=255, null=True, unique=True)),
                ('data', models.FileField(default='', null=True, upload_to=bhtom_base.bhtom_dataproducts.models.data_product_path)),
                ('status', models.CharField(choices=[('C', 'TO DO'), ('P', 'IN PROGRESS'), ('S', 'SUCCESS'), ('E', 'ERROR')], default='C', max_length=1)),
                ('photometry_data', models.URLField(default=None, null=True)),
                ('fits_data', models.URLField(default=None, null=True)),
                ('extra_data', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data_product_type', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('thumbnail', models.FileField(default=None, null=True, upload_to=bhtom_base.bhtom_dataproducts.models.data_product_path)),
                ('dryRun', models.BooleanField(default=False, verbose_name='Dry Run (no data will be stored in the database)')),
                ('comment', models.TextField(blank=True, null=True)),
                ('group', models.ManyToManyField(to='bhtom_dataproducts.dataproductgroup')),
                ('observation_record', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bhtom_observations.observationrecord')),
                ('observatory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bhtom_observatory.observatorymatrix')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom_targets.target')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': ('modified',),
            },
        ),
        migrations.CreateModel(
            name='CCDPhotJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=50)),
                ('instrument', models.CharField(blank=True, help_text='instrument identification (not used by ccdphot)', max_length=50)),
                ('instrument_prefix', models.CharField(blank=True, help_text='instrument prefix used to chose proper obsinfo', max_length=50)),
                ('webhook_id', models.CharField(blank=True, help_text='id of webhook to be fired after ccdphot processing (not implemented yet)', max_length=20)),
                ('target_name', models.CharField(blank=True, help_text='name of the target from BHTOM', max_length=100)),
                ('target_ra', models.FloatField(default=0.0, help_text='ra in decimal format', null=True)),
                ('target_dec', models.FloatField(default=0.0, help_text='dec in decimal format', null=True)),
                ('username', models.CharField(blank=True, help_text='BHTOM username', max_length=150)),
                ('hashtag', models.CharField(blank=True, help_text='CPCS hashtag', max_length=255)),
                ('dry_run', models.CharField(blank=True, default='False', help_text='in format of "True" or "False" string', max_length=5)),
                ('fits_id', models.IntegerField(default=-1, help_text='ID of the BHTOM fits file', null=True)),
                ('priority', models.IntegerField(default=0, help_text='default = 0, lower number - higher priority')),
                ('start_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('P', 'Preparation'), ('R', 'Running'), ('F', 'Finished'), ('D', 'Done'), ('E', 'Error')], default='P', editable=False, max_length=10)),
                ('status_message', models.TextField(blank=True, default='job created', editable=False)),
                ('progress', models.FloatField(default=0.0, editable=False)),
                ('fits_file', models.FileField(upload_to='fits')),
                ('ccdphot_result', models.TextField(blank=True, editable=False, null=True)),
                ('ccdphot_result_file', models.TextField(blank=True, editable=False, null=True)),
                ('ccdphot_stdout_file', models.TextField(blank=True, editable=False, null=True)),
                ('fits_object', models.CharField(max_length=70, null=True)),
                ('fits_ra', models.FloatField(default=0.0, null=True)),
                ('fits_dec', models.FloatField(default=0.0, null=True)),
                ('fits_mjd', models.FloatField(default=0.0, null=True)),
                ('fits_hjd', models.FloatField(default=0.0, null=True)),
                ('fits_exp', models.FloatField(default=0.0, null=True)),
                ('fits_filter', models.CharField(max_length=70, null=True)),
                ('fits_origin', models.CharField(max_length=70, null=True)),
                ('fits_observat', models.CharField(max_length=70, null=True)),
                ('fits_telescop', models.CharField(max_length=70, null=True)),
                ('fits_instrume', models.CharField(max_length=70, null=True)),
                ('fits_observer', models.CharField(max_length=70, null=True)),
                ('dataProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom_dataproducts.dataproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ReducedDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(default='', max_length=100)),
                ('source_name', models.CharField(db_index=True, default='', max_length=100)),
                ('source_location', models.CharField(default='', max_length=200)),
                ('mjd', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('observer', models.CharField(default='', max_length=100)),
                ('facility', models.CharField(default='', max_length=100)),
                ('value', models.FloatField(default=100)),
                ('value_list', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, null=True, size=None)),
                ('value_unit', models.CharField(choices=[('MAG', 'mag'), ('MILLIJANSKY', 'mJy'), ('ERG_S_CM2_ANGSTROM', 'erg/s/cm^2/Angstrom')], default='MAG', max_length=100)),
                ('error', models.FloatField(default=1)),
                ('error_list', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, null=True, size=None)),
                ('filter', models.CharField(default='', max_length=100)),
                ('wavelengths', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, null=True, size=None)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('active_flg', models.BooleanField(default=True)),
                ('data_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bhtom_dataproducts.dataproduct')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom_targets.target')),
            ],
            options={
                'get_latest_by': ('mjd',),
                'unique_together': {('target', 'mjd', 'value', 'error', 'filter', 'facility', 'observer')},
            },
        ),
        migrations.CreateModel(
            name='BrokerCadence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('insert_row', models.IntegerField(default=0, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom_targets.target')),
            ],
            options={
                'unique_together': {('target', 'broker_name')},
            },
        ),
    ]
