# Generated by Django 4.0.4 on 2023-09-01 08:53

import bhtom_base.bhtom_dataproducts.models
import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bhtom_observatory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bhtom_targets', '0001_initial'),
        ('bhtom_observations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('private', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DataProductGroup_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active_flg', models.BooleanField(db_index=True, default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom_dataproducts.dataproductgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(help_text='Data product identifier used by the source of the data product.', max_length=255, null=True, unique=True)),
                ('data', models.FileField(db_index=True, default=None, null=True, upload_to=bhtom_base.bhtom_dataproducts.models.data_product_path)),
                ('photometry_data', models.FileField(db_index=True, default=None, null=True, upload_to=bhtom_base.bhtom_dataproducts.models.photometry_data_product_path)),
                ('fits_data', models.FileField(db_index=True, default=None, null=True, upload_to=bhtom_base.bhtom_dataproducts.models.fits_data_product_path)),
                ('extra_data', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data_product_type', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('thumbnail', models.FileField(default=None, null=True, upload_to=bhtom_base.bhtom_dataproducts.models.data_product_path)),
                ('dryRun', models.BooleanField(default=False, verbose_name='Dry Run (no data will be stored in the database)')),
                ('group', models.ManyToManyField(to='bhtom_dataproducts.dataproductgroup')),
                ('observation_record', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bhtom_observations.observationrecord')),
                ('observatory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bhtom_observatory.observatorymatrix')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom_targets.target')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': ('modified',),
            },
        ),
        migrations.CreateModel(
            name='ReducedDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(default='', max_length=100)),
                ('source_name', models.CharField(db_index=True, default='', max_length=100)),
                ('source_location', models.CharField(default='', max_length=200)),
                ('mjd', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('observer', models.CharField(default='', max_length=100)),
                ('facility', models.CharField(default='', max_length=100)),
                ('value', models.FloatField(default=100)),
                ('value_list', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, null=True, size=None)),
                ('value_unit', models.CharField(choices=[('MAG', 'mag'), ('MILLIJANSKY', 'mJy'), ('ERG_S_CM2_ANGSTROM', 'erg/s/cm^2/Angstrom')], default='MAG', max_length=100)),
                ('error', models.FloatField(default=1)),
                ('error_list', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, null=True, size=None)),
                ('filter', models.CharField(default='', max_length=100)),
                ('wavelengths', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, null=True, size=None)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('active_flg', models.BooleanField(default=True)),
                ('data_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bhtom_dataproducts.dataproduct')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom_targets.target')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ('mjd',),
                'unique_together': {('target', 'mjd', 'value', 'error', 'filter', 'facility', 'observer')},
            },
        ),
        migrations.CreateModel(
            name='BrokerCadence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('insert_row', models.IntegerField(default=0, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom_targets.target')),
            ],
            options={
                'unique_together': {('target', 'broker_name')},
            },
        ),
    ]
