# Generated by Django 4.0.4 on 2024-03-08 15:51

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_targets', '0001_initial'),
        ('bhtom_dataproducts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectroscopyDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(default='', max_length=100)),
                ('source_location', models.CharField(blank=True, default='', max_length=200)),
                ('mjd', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('observer', models.CharField(default='', max_length=100)),
                ('facility', models.CharField(default='', max_length=100)),
                ('flux', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('flux_units', models.CharField(default='erg/(Angstrom s cm2)', max_length=50)),
                ('wavelength', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('wavelength_units', models.CharField(default='Angstrom', max_length=50)),
                ('active_flg', models.BooleanField(default=True)),
                ('data_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bhtom_dataproducts.dataproduct')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtom_targets.target')),
            ],
            options={
                'get_latest_by': ('mjd',),
                'unique_together': {('target', 'mjd', 'facility', 'observer')},
            },
        ),
    ]
