# Generated by Django 4.0.4 on 2023-10-12 15:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='data_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bhtom_dataproducts.dataproduct'),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='error_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='source_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='value_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='reduceddatum',
            name='wavelengths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, null=True, size=None),
        ),
    ]
