# Generated by Django 4.0.4 on 2024-05-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0002_spectroscopydatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduceddatum',
            name='match_distans',
            field=models.FloatField(default=0.5),
        ),
    ]
