# Generated by Django 4.0.4 on 2023-11-17 11:48

import bhtom_base.bhtom_dataproducts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_observatory', '0002_observatorymatrix_file_size'),
        ('bhtom_observations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bhtom_dataproducts', '0003_alter_ccdphotjob_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproduct',
            name='data',
            field=models.FileField(blank=True, default='', null=True, upload_to=bhtom_base.bhtom_dataproducts.models.data_product_path),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='fits_data',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='group',
            field=models.ManyToManyField(blank=True, to='bhtom_dataproducts.dataproductgroup'),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='observation_record',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bhtom_observations.observationrecord'),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='observatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bhtom_observatory.observatorymatrix'),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='photometry_data',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='thumbnail',
            field=models.FileField(blank=True, default=None, null=True, upload_to=bhtom_base.bhtom_dataproducts.models.data_product_path),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
