# Generated by Django 4.0.4 on 2024-05-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0003_reduceddatum_match_distans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reduceddatum',
            name='match_distans',
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='match_distans',
            field=models.FloatField(default=2.0),
        ),
    ]
