# Generated by Django 4.0.4 on 2023-11-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0004_alter_dataproduct_data_alter_dataproduct_fits_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccdphotjob',
            name='job_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='ccdphotjob',
            constraint=models.UniqueConstraint(fields=('job_id',), name='unique_job_id'),
        ),
    ]
