# Generated by Django 4.0.4 on 2025-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0006_ccdphotjob_use_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproduct',
            name='observers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reduceddatum',
            name='observers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='spectroscopydatum',
            name='observers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
