# Generated by Django 4.0.4 on 2025-06-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0007_dataproduct_observers_reduceddatum_observers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='observers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
