# Generated by Django 4.0.4 on 2025-09-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0008_alter_reduceddatum_observers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_airmass',
            field=models.FloatField(blank=True, help_text='AIRMASS - airmass at observation', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_bjd',
            field=models.FloatField(blank=True, help_text='BJD - Barycentric Julian Date', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_dryrun',
            field=models.CharField(blank=True, help_text='DRYRUN - dry run flag', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_filename',
            field=models.CharField(blank=True, help_text='FILENAME - original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_fwhm_av',
            field=models.FloatField(blank=True, help_text='FWHM_AV - Average Full Width Half Maximum', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_fwhm_x',
            field=models.FloatField(blank=True, help_text='FWHM_X - Full Width Half Maximum in X direction', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_fwhm_y',
            field=models.FloatField(blank=True, help_text='FWHM_Y - Full Width Half Maximum in Y direction', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_moonaz',
            field=models.FloatField(blank=True, help_text='MOONAZ - moon azimuth in degrees', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_moondist',
            field=models.FloatField(blank=True, help_text='MOONDIST - distance to moon in degrees', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_moonelev',
            field=models.FloatField(blank=True, help_text='MOONELEV - moon elevation in degrees', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_moonfrac',
            field=models.FloatField(blank=True, help_text='MOONFRAC - moon fraction (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_nodeid',
            field=models.CharField(blank=True, help_text='NODEID - processing node ID', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_numstars',
            field=models.IntegerField(blank=True, help_text='NUMSTARS - number of detected stars', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_oname',
            field=models.CharField(blank=True, help_text='ONAME - original object name', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_photflag',
            field=models.IntegerField(blank=True, help_text='PHOTFLAG - photometric flag', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_pipever',
            field=models.CharField(blank=True, help_text='PIPEVER - pipeline version', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_seeing',
            field=models.FloatField(blank=True, help_text='SEEING - atmospheric seeing in arcseconds', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_sunaz',
            field=models.FloatField(blank=True, help_text='SUNAZ - sun azimuth in degrees', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_sundist',
            field=models.FloatField(blank=True, help_text='SUNDIST - distance to sun in degrees', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_sunelev',
            field=models.FloatField(blank=True, help_text='SUNELEV - sun elevation in degrees', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_uploader',
            field=models.CharField(blank=True, help_text='UPLOADER - who uploaded the file', max_length=70, null=True),
        ),
    ]
