# Generated by Django 4.0.4 on 2025-09-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0009_ccdphotjob_fits_airmass_ccdphotjob_fits_bjd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_glim',
            field=models.FloatField(blank=True, help_text='GLIM', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_toiifov',
            field=models.CharField(blank=True, help_text='TOIIFOV - TOI Input Field of View', max_length=70, null=True),
        ),
    ]
