# Generated by Django 4.0.4 on 2025-09-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0010_ccdphotjob_fits_glim_ccdphotjob_fits_toiifov'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_altitude',
            field=models.FloatField(blank=True, help_text='ALTITUDE - altitude of the observation site in meters', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_azimuth',
            field=models.FloatField(blank=True, help_text='AZIMUTH - azimuth of the observation site in degrees', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_binning',
            field=models.IntegerField(blank=True, help_text='BINNING - binning factor', null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_dateobs',
            field=models.CharField(blank=True, help_text='DATE-OBS - date of observation', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_pixscale',
            field=models.FloatField(blank=True, help_text='PIXELSCALE - pixel scale in arcseconds/pixel', null=True),
        ),
        migrations.AlterField(
            model_name='ccdphotjob',
            name='fits_dec',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ccdphotjob',
            name='fits_exp',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ccdphotjob',
            name='fits_filter',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='ccdphotjob',
            name='fits_hjd',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ccdphotjob',
            name='fits_instrume',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='ccdphotjob',
            name='fits_mjd',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ccdphotjob',
            name='fits_object',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='ccdphotjob',
            name='fits_observat',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='ccdphotjob',
            name='fits_observer',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='ccdphotjob',
            name='fits_origin',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='ccdphotjob',
            name='fits_ra',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ccdphotjob',
            name='fits_telescop',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
