# Generated by Django 4.0.4 on 2026-01-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0011_ccdphotjob_fits_altitude_ccdphotjob_fits_azimuth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatum',
            name='value_unit',
            field=models.CharField(choices=[('MAG', 'mag'), ('MILLIJANSKY', 'mJy'), ('ERG_S_CM2_ANGSTROM', 'erg/s/cm^2/Angstrom'), ('COUNTS', 'cts'), ('FLUX', 'erg/s/cm^2')], default='MAG', max_length=100),
        ),
    ]
