# Generated by Django 4.0.4 on 2026-08-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0012_alter_reduceddatum_value_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccdphotjob',
            name='fits_commflag',
            field=models.IntegerField(blank=True, help_text='COMMFLAG - communication flag', null=True),
        ),
    ]
