# Generated by Django 4.0.4 on 2026-08-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_dataproducts', '0013_ccdphotjob_fits_commflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccdphotjob',
            name='fits_commflag',
            field=models.CharField(blank=True, help_text='COMMFLAG - communication flag', max_length=255, null=True),
        ),
    ]
